"""Adding status in subtasks

Revision ID: 222079985df6
Revises: 9caaf1345ede
Create Date: 2020-01-10 15:22:13.749063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222079985df6'
down_revision = '9caaf1345ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtask', sa.Column('status', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_subtask_status'), 'subtask', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtask_status'), table_name='subtask')
    op.drop_column('subtask', 'status')
    # ### end Alembic commands ###
