"""count of no of subtasks

Revision ID: 319f990ad5a5
Revises: 222079985df6
Create Date: 2020-01-13 22:06:03.620444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319f990ad5a5'
down_revision = '222079985df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('n_subtasks', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('nc_subtasks', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_task_n_subtasks'), 'task', ['n_subtasks'], unique=False)
    op.create_index(op.f('ix_task_nc_subtasks'), 'task', ['nc_subtasks'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_nc_subtasks'), table_name='task')
    op.drop_index(op.f('ix_task_n_subtasks'), table_name='task')
    op.drop_column('task', 'nc_subtasks')
    op.drop_column('task', 'n_subtasks')
    # ### end Alembic commands ###
